-- Fresh-install baseline. Later migrations intentionally evolve this schema so
-- existing databases can be baselined without replacing or losing metadata.
CREATE TABLE `databases` (
    database_id VARCHAR(32) NOT NULL,
    operation_id VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    project_name VARCHAR(30) NOT NULL,
    namespace_name VARCHAR(63) NOT NULL,
    display_name VARCHAR(32) NOT NULL,
    remark VARCHAR(64) NULL,
    engine VARCHAR(32) NULL,
    mode VARCHAR(32) NULL,
    database_version VARCHAR(32) NOT NULL,
    size_plan VARCHAR(32) NULL,
    storage_gi INT NOT NULL,
    deletion_protection BOOLEAN NOT NULL,
    desired_status VARCHAR(32) NULL,
    status VARCHAR(32) NULL,
    kubeblocks_phase VARCHAR(32) NULL,
    expected_replicas INT NOT NULL DEFAULT 0,
    observed_ready_replicas INT NOT NULL DEFAULT 0,
    observed_service_ready BOOLEAN NOT NULL DEFAULT FALSE,
    provisioning_stage VARCHAR(32) NOT NULL,
    progress INT NOT NULL,
    replicas INT NOT NULL DEFAULT 0,
    shards INT NOT NULL DEFAULT 0,
    timezone VARCHAR(60) NULL,
    allowed_cidrs VARCHAR(1000) NULL,
    public_port INT NULL,
    tags VARCHAR(2000) NULL,
    message VARCHAR(4000) NULL,
    sync_message VARCHAR(4000) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    last_observed_at DATETIME(6) NULL,
    missing_since DATETIME(6) NULL,
    degraded_since DATETIME(6) NULL,
    delete_requested_at DATETIME(6) NULL,
    deleted_at DATETIME(6) NULL,
    PRIMARY KEY (database_id),
    CONSTRAINT uk_database_project_idempotency UNIQUE (project_name, idempotency_key)
) ENGINE=InnoDB;

CREATE TABLE projects (
    project_id VARCHAR(32) NOT NULL,
    project_name VARCHAR(30) NOT NULL,
    display_name VARCHAR(64) NOT NULL,
    description VARCHAR(250) NULL,
    namespace_name VARCHAR(63) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (project_id),
    CONSTRAINT uk_project_name UNIQUE (project_name)
) ENGINE=InnoDB;

CREATE TABLE operations (
    operation_id VARCHAR(32) NOT NULL,
    database_id VARCHAR(32) NOT NULL,
    project_name VARCHAR(30) NOT NULL,
    type VARCHAR(32) NULL,
    status VARCHAR(32) NULL,
    provisioning_stage VARCHAR(32) NOT NULL,
    progress INT NOT NULL,
    message VARCHAR(4000) NULL,
    idempotency_key VARCHAR(128) NULL,
    request_hash VARCHAR(64) NULL,
    ops_request_name VARCHAR(63) NULL,
    component_name VARCHAR(63) NULL,
    target_replicas INT NULL,
    target_storage_size VARCHAR(32) NULL,
    volume_name VARCHAR(32) NULL,
    cpu_request VARCHAR(32) NULL,
    memory_request VARCHAR(32) NULL,
    cpu_limit VARCHAR(32) NULL,
    memory_limit VARCHAR(32) NULL,
    created_at DATETIME(6) NULL,
    started_at DATETIME(6) NULL,
    completed_at DATETIME(6) NULL,
    PRIMARY KEY (operation_id)
) ENGINE=InnoDB;
