-- Backup and restore are desired-state records. KubeBlocks remains the
-- observed infrastructure authority; these rows never contain object-storage
-- credentials, encryption keys, Kubernetes Secrets, or database passwords.

CREATE TABLE backup_policies (
    policy_id VARCHAR(32) NOT NULL,
    project_name VARCHAR(32) NOT NULL,
    database_id VARCHAR(32) NOT NULL,
    engine VARCHAR(32) NOT NULL,
    kubernetes_policy_name VARCHAR(63) NOT NULL,
    backup_repository_name VARCHAR(63) NOT NULL,
    default_backup_method VARCHAR(63) NOT NULL,
    encryption_configured BOOLEAN NOT NULL DEFAULT FALSE,
    scheduling_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    cron_expression VARCHAR(128) NULL,
    default_retention_period VARCHAR(32) NOT NULL,
    observed_status VARCHAR(32) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (policy_id),
    CONSTRAINT uk_backup_policy_project_database UNIQUE (project_name, database_id),
    INDEX idx_backup_policies_database (database_id)
) ENGINE=InnoDB;

CREATE TABLE backups (
    backup_id VARCHAR(32) NOT NULL,
    operation_id VARCHAR(32) NOT NULL,
    delete_operation_id VARCHAR(32) NULL,
    project_name VARCHAR(32) NOT NULL,
    database_id VARCHAR(32) NOT NULL,
    source_display_name VARCHAR(32) NOT NULL,
    engine VARCHAR(32) NOT NULL,
    backup_type VARCHAR(32) NOT NULL,
    parent_backup_id VARCHAR(32) NULL,
    backup_chain_id VARCHAR(32) NOT NULL,
    kubernetes_backup_name VARCHAR(63) NOT NULL,
    kubernetes_policy_name VARCHAR(63) NULL,
    backup_repository_name VARCHAR(63) NOT NULL,
    status VARCHAR(32) NOT NULL,
    retention_period VARCHAR(32) NOT NULL,
    size_bytes BIGINT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    failure_code VARCHAR(64) NULL,
    failure_message VARCHAR(1000) NULL,
    source_mode VARCHAR(32) NOT NULL,
    source_database_version VARCHAR(32) NOT NULL,
    source_size_plan VARCHAR(32) NOT NULL,
    source_storage_gi INT NOT NULL,
    source_replicas INT NOT NULL,
    source_shards INT NOT NULL,
    source_timezone VARCHAR(60) NULL,
    source_allowed_cidrs VARCHAR(1000) NULL,
    source_tags VARCHAR(2000) NULL,
    created_at DATETIME(6) NOT NULL,
    started_at DATETIME(6) NULL,
    completed_at DATETIME(6) NULL,
    delete_requested_at DATETIME(6) NULL,
    deleted_at DATETIME(6) NULL,
    last_observed_at DATETIME(6) NULL,
    PRIMARY KEY (backup_id),
    CONSTRAINT uk_backups_project_database_idempotency
        UNIQUE (project_name, database_id, idempotency_key),
    CONSTRAINT uk_backups_kubernetes_name UNIQUE (kubernetes_backup_name),
    INDEX idx_backups_project_database_created (project_name, database_id, created_at),
    INDEX idx_backups_status_created (status, created_at),
    INDEX idx_backups_chain (backup_chain_id)
) ENGINE=InnoDB;

CREATE TABLE restore_requests (
    restore_id VARCHAR(32) NOT NULL,
    operation_id VARCHAR(32) NOT NULL,
    project_name VARCHAR(32) NOT NULL,
    source_database_id VARCHAR(32) NOT NULL,
    source_backup_id VARCHAR(32) NOT NULL,
    restored_database_id VARCHAR(32) NOT NULL,
    engine VARCHAR(32) NOT NULL,
    restore_time DATETIME(6) NULL,
    kubernetes_ops_request_name VARCHAR(63) NOT NULL,
    kubernetes_cluster_name VARCHAR(63) NOT NULL,
    status VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    failure_code VARCHAR(64) NULL,
    failure_message VARCHAR(1000) NULL,
    created_at DATETIME(6) NOT NULL,
    started_at DATETIME(6) NULL,
    completed_at DATETIME(6) NULL,
    last_observed_at DATETIME(6) NULL,
    PRIMARY KEY (restore_id),
    CONSTRAINT uk_restore_project_backup_idempotency
        UNIQUE (project_name, source_backup_id, idempotency_key),
    CONSTRAINT uk_restore_target_database UNIQUE (restored_database_id),
    CONSTRAINT uk_restore_ops_request UNIQUE (kubernetes_ops_request_name),
    INDEX idx_restore_project_source_backup (project_name, source_backup_id),
    INDEX idx_restore_status_created (status, created_at)
) ENGINE=InnoDB;
